
export default [
    {
        "id": "1",
        "title": "Black Panther",
        "year": "2018",
        "genres": [
            "Action",
            "Adventure",
            "Sci-Fi"
        ],
        "ratings": [
            4,
            1,
            9,
            6,
            2,
            10,
            6,
            5,
            1,
            7,
            4,
            5,
            6,
            5,
            6,
            3,
            10,
            10,
            8,
            2,
            5,
            3,
            4,
            6,
            6,
            7,
            9,
            4,
            4,
            9
        ],
        "poster": "MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT134M",
        "releaseDate": "2018-02-14",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "After the events of Captain America: Civil War, King T'Challa returns home to the reclusive, technologically advanced African nation of Wakanda to serve as his country's new leader. However, T'Challa soon finds that he is challenged for the throne from factions within his own country. When two foes conspire to destroy Wakanda, the hero known as Black Panther must team up with C.I.A. agent Everett K. Ross and members of the Dora Milaje, Wakandan special forces, to prevent Wakanda from being dragged into a world war.                Written by\nEditor",
        "actors": [
            "Chadwick Boseman",
            "Michael B. Jordan",
            "Lupita Nyong'o"
        ],
        "imdbRating": 7.0,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "2",
        "title": "Grottmannen Dug",
        "year": "2018",
        "genres": [
            "Animation",
            "Adventure",
            "Comedy"
        ],
        "ratings": [
            7,
            9,
            6,
            1,
            3,
            8,
            3,
            8,
            7,
            6,
            10,
            3,
            6,
            8,
            3,
            5,
            6,
            6,
            8,
            2,
            7,
            9,
            1,
            1,
            10,
            2,
            3,
            6,
            3,
            5
        ],
        "poster": "MV5BYWMxYWVjNzAtMTY0YS00YWQyLWExMGItMjUxODkwYzQyNzMwXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SY500_CR0,0,328,500_AL_.jpg",
        "contentRating": "PG",
        "duration": "PT89M",
        "releaseDate": "2018-03-23",
        "averageRating": 0,
        "originalTitle": "Early Man",
        "desc": "Set at the dawn of time, when prehistoric creatures and woolly mammoths roamed the earth, Early Man tells the story of Dug, along with sidekick Hognob as they unite his tribe against a mighty enemy Lord Nooth and his Bronze Age City to save their home.",
        "actors": [
            "Tom Hiddleston",
            "Eddie Redmayne",
            "Maisie Williams"
        ],
        "imdbRating": 6.3,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BYWMxYWVjNzAtMTY0YS00YWQyLWExMGItMjUxODkwYzQyNzMwXkEyXkFqcGdeQXVyMjMxOTE0ODA@._V1_SY500_CR0,0,328,500_AL_.jpg"
    },
    {
        "id": "3",
        "title": "Aiyaary",
        "year": "2018",
        "genres": [
            "Action",
            "Crime",
            "Drama"
        ],
        "ratings": [
            1,
            2,
            8,
            10,
            3,
            8,
            8,
            6,
            1,
            8,
            4,
            1,
            9,
            5,
            7,
            8,
            9,
            8,
            10,
            10,
            8,
            3,
            1,
            2,
            5,
            7,
            9,
            9,
            10,
            7
        ],
        "poster": "MV5BMjI1NTk0NTc1OV5BMl5BanBnXkFtZTgwNTMwMTE4NDM@._V1_SY500_CR0,0,281,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT157M",
        "releaseDate": "2018-02-16",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "Two officers with patriotic hearts suddenly have a fallout. The mentor, Colonel Abhay Singh has complete faith in the country's system while prot\u00e9g\u00e9 Major Jai Bakshi thinks differently due to a recent stint in surveillance.",
        "actors": [
            "Anupam Kher",
            "Sidharth Malhotra",
            "Naseeruddin Shah"
        ],
        "imdbRating": "",
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjI1NTk0NTc1OV5BMl5BanBnXkFtZTgwNTMwMTE4NDM@._V1_SY500_CR0,0,281,500_AL_.jpg"
    },
    {
        "id": "4",
        "title": "Samson",
        "year": "2018",
        "genres": [
            "Action",
            "Drama"
        ],
        "ratings": [
            9,
            6,
            5,
            7,
            5,
            8,
            9,
            7,
            1,
            1,
            9,
            2,
            9,
            7,
            8,
            7,
            5,
            3,
            3,
            1,
            2,
            10,
            10,
            2,
            1,
            9,
            6,
            8,
            6,
            8
        ],
        "poster": "MV5BYThiMjg4ZDAtNjk5ZS00ZTUxLThmM2ItMGI0ZTE1NjRhNWNmXkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SY500_CR0,0,334,500_AL_.jpg",
        "contentRating": "PG-13",
        "duration": "",
        "releaseDate": "2018-02-16",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "A Hebrew with an unusual gift of strength must respond properly to the call of God on his life in order to lead his people out of enslavement. After his youthful ambition leads to a tragic marriage, his acts of revenge thrust him into direct conflict with the Philistine army. As his brother mounts a tribal rebellion, only Samson's relationship with a Philistine seductress and his final surrender - both to the Philistines and to God - turns imprisonment and blindness into final victory.                Written by\nPure Flix",
        "actors": [
            "Jackson Rathbone",
            "Billy Zane",
            "Taylor James"
        ],
        "imdbRating": 5.0,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BYThiMjg4ZDAtNjk5ZS00ZTUxLThmM2ItMGI0ZTE1NjRhNWNmXkEyXkFqcGdeQXVyNTQ3MjE4NTU@._V1_SY500_CR0,0,334,500_AL_.jpg"
    },
    {
        "id": "5",
        "title": "Loveless",
        "year": "2017",
        "genres": [
            "Drama"
        ],
        "ratings": [
            7,
            5,
            7,
            6,
            10,
            8,
            8,
            7,
            3,
            7,
            3,
            4,
            5,
            10,
            8,
            10,
            1,
            7,
            2,
            10,
            10,
            3,
            5,
            2,
            9,
            7,
            7,
            3,
            5,
            1
        ],
        "poster": "MV5BMzU3ODQ3MzQ5Nl5BMl5BanBnXkFtZTgwMDQwMDIzNDM@._V1_SY500_CR0,0,338,500_AL_.jpg",
        "contentRating": "R",
        "duration": "PT127M",
        "releaseDate": "2017-06-01",
        "averageRating": 0,
        "originalTitle": "Nelyubov",
        "desc": "Still living under the same roof, the Moscow couple of Boris and Zhenya is in the terrible final stages of a bitter divorce. Under those circumstances, as both have already found new partners, the insults pour down like rain in this toxic familial battle zone, always pivoting around the irresolvable and urgent matter of Alyosha's custody, their 12-year-old only son. Unheard, unloved, and above all, unwanted, the introverted and unhappy boy feels that he is an intolerable burden, however, what his parents don't know is that he can hear every single word. As a result, when Boris and Zhenya finally realize that Alyosha has been missing for nearly two days, it is already too late. But is this a simple case of a runaway teenager?                Written by\nNick Riganas",
        "actors": [
            "Maryana Spivak",
            "Aleksey Rozin",
            "Matvey Novikov"
        ],
        "imdbRating": 7.8,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzU3ODQ3MzQ5Nl5BMl5BanBnXkFtZTgwMDQwMDIzNDM@._V1_SY500_CR0,0,338,500_AL_.jpg"
    },
    {
        "id": "6",
        "title": "L'amant double",
        "year": "2017",
        "genres": [
            "Drama",
            "Romance",
            "Thriller"
        ],
        "ratings": [
            5,
            8,
            9,
            8,
            10,
            2,
            7,
            2,
            9,
            8,
            5,
            1,
            9,
            5,
            9,
            5,
            7,
            10,
            5,
            8,
            2,
            3,
            5,
            4,
            6,
            9,
            3,
            7,
            1,
            4
        ],
        "poster": "MV5BMTg5NjUyMzAyOV5BMl5BanBnXkFtZTgwMTU4Njk2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT107M",
        "releaseDate": "2017-05-26",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "Disenchanted with the ephemeral glamour of the modelling world, Chlo\u00e9, a vulnerable Parisian woman of 25, is convinced that the severe and persistent abdominal pains she's been suffering, stem mainly from a psychosomatic disorder. As a result, the reserved beauty will soon find herself on the couch of the charming therapist, Dr Paul Meyer, nevertheless, the mutual and unfailing sexual attraction between them will make it impossible to continue with the therapy. Before long, the ecstatic, yet unexplored lovers will move in together, however, Paul's obscure past will inevitably lead Chlo\u00e9 to the conclusion that there's definitely more to him than meets the eye. Is the doe-eyed woman lured into a world of hallucinations and dream-like sequences?                Written by\nNick Riganas",
        "actors": [
            "Marine Vacth",
            "J\u00e9r\u00e9mie Renier",
            "Jacqueline Bisset"
        ],
        "imdbRating": 6.2,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg5NjUyMzAyOV5BMl5BanBnXkFtZTgwMTU4Njk2NDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "7",
        "title": "The Party",
        "year": "2017",
        "genres": [
            "Comedy",
            "Drama"
        ],
        "ratings": [
            1,
            4,
            3,
            3,
            1,
            4,
            6,
            5,
            8,
            3,
            8,
            5,
            9,
            9,
            8,
            6,
            9,
            2,
            2,
            10,
            8,
            2,
            8,
            9,
            3,
            6,
            10,
            8,
            9,
            9
        ],
        "poster": "MV5BMTYwMTU5MzY4NF5BMl5BanBnXkFtZTgwNTY2NTkxNDM@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "11",
        "duration": "PT71M",
        "releaseDate": "2018-01-05",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "To celebrate her long-awaited prestigious post as a Shadow Minister for Health and, hopefully, the stepping stone to party leadership, the newly-appointed British opposition politician, Janet, is throwing a party for friends at her London flat. Of course, in this select and intimate soir\u00e9e, apart from Bill--Janet's self-denying academic husband--a motley crew of elite hand-picked guests have been invited: There's April, the sourly cynical American best friend; her unlikely German husband, Gottfried; there's also Jinny and Martha; and finally, Tom, the smooth banker in the impeccable suit. But inevitably, before dinner is served, the upbeat ambience will shatter to pieces, as festering secrets will start surfacing in this perfect domestic war-zone. Undoubtedly, after this night, things will never be the same again.                Written by\nNick Riganas",
        "actors": [
            "Timothy Spall",
            "Kristin Scott Thomas",
            "Patricia Clarkson"
        ],
        "imdbRating": 6.7,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTYwMTU5MzY4NF5BMl5BanBnXkFtZTgwNTY2NTkxNDM@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "8",
        "title": "The Boy Downstairs",
        "year": "2017",
        "genres": [
            "Comedy",
            "Drama",
            "Romance"
        ],
        "ratings": [
            6,
            5,
            8,
            5,
            8,
            3,
            2,
            4,
            4,
            1,
            8,
            5,
            5,
            1,
            9,
            8,
            1,
            1,
            9,
            10,
            9,
            8,
            4,
            10,
            3,
            6,
            2,
            8,
            9,
            8
        ],
        "poster": "MV5BNjZiNzgzNjUtOWE0Ni00MWFmLTliZDEtNWRkMzc5ZTA2MWM1XkEyXkFqcGdeQXVyNDExMzMxNjE@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "PG-13",
        "duration": "PT91M",
        "releaseDate": "2018-02-16",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "A young woman is forced to reflect on her first relationship when she inadvertently moves into her ex-boyfriend's apartment building.",
        "actors": [
            "Zosia Mamet",
            "Matthew Shear",
            "Deirdre O'Connell"
        ],
        "imdbRating": 6.9,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BNjZiNzgzNjUtOWE0Ni00MWFmLTliZDEtNWRkMzc5ZTA2MWM1XkEyXkFqcGdeQXVyNDExMzMxNjE@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "9",
        "title": "Nostalgia",
        "year": "2018",
        "genres": [
            "Drama"
        ],
        "ratings": [
            5,
            1,
            10,
            9,
            6,
            9,
            6,
            6,
            4,
            3,
            6,
            6,
            7,
            5,
            3,
            5,
            4,
            6,
            4,
            7,
            7,
            1,
            10,
            9,
            7,
            3,
            4,
            4,
            3,
            10
        ],
        "poster": "MV5BYTc0MjI4YTktY2NkYi00YzgwLWIxNDItYWIyNjAwMWNlMGUzXkEyXkFqcGdeQXVyNDY2MjcyOTQ@._V1_SY500_CR0,0,337,500_AL_.jpg",
        "contentRating": "R",
        "duration": "PT114M",
        "releaseDate": "2018-02-16",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "A mosaic of stories about love and loss, 'Nostalgia' explores our relationships to the objects, artifacts, and memories that shape our lives.",
        "actors": [
            "Hugo Armstrong",
            "Shinelle Azoroh",
            "Annalise Basso"
        ],
        "imdbRating": 6.6,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BYTc0MjI4YTktY2NkYi00YzgwLWIxNDItYWIyNjAwMWNlMGUzXkEyXkFqcGdeQXVyNDY2MjcyOTQ@._V1_SY500_CR0,0,337,500_AL_.jpg"
    },
    {
        "id": "10",
        "title": "Oh Lucy!",
        "year": "2017",
        "genres": [
            "Comedy",
            "Drama"
        ],
        "ratings": [
            10,
            4,
            7,
            10,
            8,
            4,
            6,
            10,
            2,
            10,
            9,
            8,
            8,
            3,
            3,
            6,
            6,
            3,
            5,
            4,
            5,
            4,
            5,
            2,
            2,
            8,
            5,
            10,
            2,
            9
        ],
        "poster": "MV5BMTUzMjcwMDExOV5BMl5BanBnXkFtZTgwMjU4Njk2NDM@._V1_SY377_CR0,0,254,377_AL_.jpg",
        "contentRating": "",
        "duration": "PT95M",
        "releaseDate": "2018-03-02",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "The drama-comedy tells the story of Setsuko Kawashima (Terajima), a lonely, chain-smoking office lady in Tokyo who is past her prime. After deciding to take an English class, she discovers a new identity in her American alter ego, 'Lucy,' and falls for her instructor, John (Hartnett). When John suddenly disappears, Setsuko earnestly sets out on a quest to find him, eventually leading her to the outskirts of Southern California.                Written by\nOh Lucy!",
        "actors": [
            "Shinobu Terajima",
            "Josh Hartnett",
            "Kaho Minami"
        ],
        "imdbRating": 6.8,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUzMjcwMDExOV5BMl5BanBnXkFtZTgwMjU4Njk2NDM@._V1_SY377_CR0,0,254,377_AL_.jpg"
    },
    {
        "id": "11",
        "title": "Tehran Taboo",
        "year": "2017",
        "genres": [
            "Animation",
            "Drama"
        ],
        "ratings": [
            3,
            6,
            1,
            4,
            9,
            10,
            7,
            5,
            2,
            8,
            9,
            7,
            5,
            10,
            9,
            1,
            10,
            4,
            6,
            7,
            3,
            10,
            3,
            6,
            3,
            10,
            6,
            4,
            1,
            10
        ],
        "poster": "MV5BZDM0OTZlOWQtZGU0My00MmIxLTk0N2ItMjU3OGY0ODRlODYxXkEyXkFqcGdeQXVyNTQ0NjIwNDU@._V1_SY500_CR0,0,353,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT90M",
        "releaseDate": "2017-11-16",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "In their desperate search for freedom and happiness, four young people from Tehran, Iran are forced to break the taboos of a restrictive, islamic society.",
        "actors": [
            "Farhad Abadinejad",
            "Jasmina Ali",
            "Rozita Assadollahy"
        ],
        "imdbRating": 7.1,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BZDM0OTZlOWQtZGU0My00MmIxLTk0N2ItMjU3OGY0ODRlODYxXkEyXkFqcGdeQXVyNTQ0NjIwNDU@._V1_SY500_CR0,0,353,500_AL_.jpg"
    },
    {
        "id": "12",
        "title": "Xiyouji zhi N\u00fc'erguo",
        "year": "2018",
        "genres": [
            "Action",
            "Adventure",
            "Fantasy"
        ],
        "ratings": [
            10,
            6,
            1,
            4,
            8,
            2,
            2,
            4,
            10,
            10,
            6,
            5,
            5,
            7,
            2,
            3,
            1,
            3,
            2,
            10,
            2,
            3,
            2,
            10,
            9,
            9,
            8,
            9,
            6,
            4
        ],
        "poster": "MV5BMDM1MzZjNDUtNDBmMC00M2M5LTg0NDQtN2ExMjQ1Zjc0ZTE0XkEyXkFqcGdeQXVyNjMyMDA1ODM@._V1_SY500_CR0,0,357,500_AL_.jpg",
        "contentRating": "",
        "duration": "",
        "releaseDate": "2018-02-16",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "",
        "actors": [
            "Aaron Kwok",
            "William Feng",
            "Zanilia Zhao"
        ],
        "imdbRating": "",
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BMDM1MzZjNDUtNDBmMC00M2M5LTg0NDQtN2ExMjQ1Zjc0ZTE0XkEyXkFqcGdeQXVyNjMyMDA1ODM@._V1_SY500_CR0,0,357,500_AL_.jpg"
    },
    {
        "id": "13",
        "title": "Mind Game",
        "year": "2004",
        "genres": [
            "Animation",
            "Adventure",
            "Comedy"
        ],
        "ratings": [
            8,
            6,
            5,
            7,
            10,
            7,
            9,
            5,
            9,
            3,
            6,
            10,
            7,
            4,
            2,
            4,
            7,
            7,
            5,
            8,
            9,
            3,
            9,
            7,
            9,
            4,
            8,
            5,
            2,
            8
        ],
        "poster": "MV5BNzFlMDI1ZjctMzgzYy00YmVkLTlmMTMtNDZmZmVmMzk3MzNhXkEyXkFqcGdeQXVyMTA1OTEwNjE@._V1_SY500_CR0,0,381,500_AL_.jpg",
        "contentRating": "",
        "duration": "PT103M",
        "releaseDate": "2004-07-28",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "The film follows Nishi, a loser who has a crush on his childhood girlfriend. After an encounter with the Japanese mafia, the film follows Nishi as he journeys to heaven and back, and ends up trapped in an even more unlikely place. Nishi (and some friends) attempt to break out of their trap, and discover what it truly means to be alive along the way. This is a mind-bending trip that uses some of the most innovative animation ever created.                Written by\nanimenewsnetwork.com",
        "actors": [
            "K\u00f4ji Imada",
            "Sayaka Maeda",
            "Takashi Fujii"
        ],
        "imdbRating": 7.9,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzFlMDI1ZjctMzgzYy00YmVkLTlmMTMtNDZmZmVmMzk3MzNhXkEyXkFqcGdeQXVyMTA1OTEwNjE@._V1_SY500_CR0,0,381,500_AL_.jpg"
    },
    {
        "id": "14",
        "title": "Western",
        "year": "2017",
        "genres": [
            "Drama"
        ],
        "ratings": [
            3,
            6,
            4,
            2,
            10,
            5,
            1,
            9,
            7,
            9,
            10,
            6,
            3,
            2,
            10,
            5,
            10,
            7,
            1,
            5,
            6,
            10,
            9,
            9,
            10,
            4,
            8,
            8,
            3,
            9
        ],
        "poster": "MV5BZDRkZGUxZmEtZDdiZC00NGJmLWFiODAtN2RiMzY3ODhjNTNmXkEyXkFqcGdeQXVyMTg5MDEyNw@@._V1_SY500_CR0,0,341,500_AL_.jpg",
        "contentRating": "15",
        "duration": "PT119M",
        "releaseDate": "2017-08-24",
        "averageRating": 0,
        "originalTitle": "",
        "desc": "A group of German construction workers start a tough job at a remote site in the Bulgarian countryside. The foreign land awakens the men's sense of adventure, but they are also confronted with their own prejudice and mistrust due to the language barrier and cultural differences. The stage is quickly set for a showdown when men begin to compete for recognition and favor from the local villagers.",
        "actors": [
            "Meinhard Neumann",
            "Reinhardt Wetrek",
            "Syuleyman Alilov Letifov"
        ],
        "imdbRating": 7.2,
        "image": "https://images-na.ssl-images-amazon.com/images/M/MV5BZDRkZGUxZmEtZDdiZC00NGJmLWFiODAtN2RiMzY3ODhjNTNmXkEyXkFqcGdeQXVyMTg5MDEyNw@@._V1_SY500_CR0,0,341,500_AL_.jpg"
    },
]